/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as govTokenSol from "./GovToken.sol";
export type { govTokenSol };
import type * as governanceStandard from "./governance_standard";
export type { governanceStandard };
export type { Box } from "./Box";
