/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as govTokenSol from "./GovToken.sol";
export * as governanceStandard from "./governance_standard";
export { Box__factory } from "./Box__factory";
